### ISSUE TITLE
Add a website

### ISSUE THREAD

**Issue by EternityWorkTogether** [Randomblock1/unblock-survivio#10]
**What is the website you want to add to this repo? (Include URL)**
Ex. coolmathgames.com

**What does the website you are trying to add do?**
Ex. epic

**Did you create a fork adding the things you want and make a pull request?**
np

**Additional context**
Add any other context or screenshots about the website here.

**Comment by Randomblock1** [comment]
I added it, haven’t tested it though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
