### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by kriosiss** [Randomblock1/unblock-survivio#11]
its still blocked

**Comment by Randomblock1** [comment]
cool story bro

Do you mind actually giving any more information? If you go to surviv.io is it blocked by Securly or something else? If it’s not blocked by Securly your school is doing it, and I can’t bypass that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kriosiss** [comment]
![21A52953-E70D-4488-9A3F-B05BBFBCA98B](https://user-images.githubusercontent.com/55456098/65174906-d3935400-da1f-11e9-9995-43d7368707f8.jpeg)

**Comment by kriosiss** [comment]
That’s what they use

**Comment by Randomblock1** [comment]
Not an issue with this project. Please read the README in its entiretyz

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
