### ISSUE TITLE
ISSUE WITH SURVIV.IO

### ISSUE THREAD

**Issue by Helixable** [Randomblock1/unblock-survivio#7]
The webpage at https://surviv.io/ might be temporarily down or it may have moved permanently to a new web address.

Tht's what it sais....
It might be the school blocking, but any way to get past it?

**Comment by Randomblock1** [comment]
That’s your school specifically blocking IPs. This tool is only made to bypass Securly, and is not meant to bypass IP blocking. Try searching for a Glype proxy, those might help you out. I use [this one](tonernews.com/glype).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Helixable** [comment]
Yea, but I use a Chromebook. SO I can't install any apps.

**Comment by Randomblock1** [comment]
Your school blocks IPs and this tool doesn’t bypass that. Glype proxies are websites you can use to bypass IP filters. This tool is ONLY meant to bypass Securly, and it is not meant to bypass apps or anything.
