### ISSUE TITLE
Most sites broken

### ISSUE THREAD

**Issue by Owenm06** [Randomblock1/unblock-survivio#8]
Hello! I like this site, and I think it has lots of potential! I have found one thing:
Bing is the only one to work. The others just have the frame filled in with white. I’m on an IPad with safari. Good luck!

**Comment by Randomblock1** [comment]
Please see Issue #6. I don’t know what the problem is with iPads and Securly. My guess is that the Securly app blocks IPs where the Chrome extension doesn’t check iframes. Don’t have the app or an iPad to test it, but that’s likely the case. Will investigate later.

**Comment by Randomblock1** [comment]
Figured out that IP blocking is actually what the iPad app does. Can’t get around that with this website. I’ll update the README to specify what it can and cannot work on.
Won’t fix, can’t fix. This is simply an HTML website and I can’t help you with that.
