### ISSUE TITLE
Nice try at not making it fullscreen

### ISSUE THREAD

**Issue by WhiteFireWisp** [Randomblock1/unblock-survivio#9]
for anyone who sees this issue just change the iframe height to 100% to get a full image, alternatively you can use my repo that has the fullscreen version

**Comment by Randomblock1** [comment]
this should have been some sort of pull request, not an issue.
I’ll fix it though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Randomblock1** [comment]
idk why that was marked invalid. fixed it though, forgot to close the issue.
